spring:
        profiles:
          active: local

# Local
---
spring:
  config:
    activate:
      on-profiles: local #spring-boot 2.4 ??
  datasource:
#    data: classpath:data-h2.sql
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE  # H2 ?? ??
    username: admin  # H2 ?? ? ??? username ?? (??? ??? ??)
    password: 1234 # H2 ?? ?
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true #데이터베이스 생성전 인서트실행방지
  h2:
    console:
      enabled: true
#      path: /h2-console ?? 8080?? ??
  main:
    allow-circular-references: true
  #Thymeleaf
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  sql:
    init:
      data-locations: classpath:data.sql # 데이터베이스 기본값 추가하기위함

logging:
  level: # ? package ?? ?? ??? ??? ? ??.
#    org.hibernate.type: trace                   # ???? ??? ????? ? ? ?? ?? ??
#    org.hibernate.SQL: debug                    # logger? ?? ?????? ?? SQL
    org.hibernate.type.descriptor.sql: trace    # sql? ? ?? Parameter? ???.