INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (200, 'HELLO1', 1, CURRENT_TIMESTAMP,'HITMAN', 10, 'GOODJOB1', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (201, 'HELLO2', 3, CURRENT_TIMESTAMP,'HITMAN2', 9, 'GOODJOB22', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (202, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (203, '징동다운굿', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (204, '징동다운444', 4111, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (205, '징동다운', 41, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (206, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (207, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (208, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (209, '징동다515운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (210, '징동굿다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO3', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (211, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWO55O', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (212, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN오오', 5, 'NAKWㅒㅖOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (213, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (214, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (215, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (216, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (217, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (218, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (219, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (220, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (221, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (222, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (223, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (224, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (225, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (226, '화이팅123이다라고', 6, CURRENT_TIMESTAMP,'헬로우보이11비밥', 5, '굿보이1441', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (227, '화이팅이다라고', 8, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이112', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (228, '화이팅이다라고23', 441, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (229, 'ohwowo', 50, CURRENT_TIMESTAMP,'헬로우보이비밥', 500, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (230, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (231, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (232, '화이팅이다라고', 84, CURRENT_TIMESTAMP,'헬로우보이비밥', 51, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (233, '화이팅이다라고', 54, CURRENT_TIMESTAMP,'헬로우보이비밥', 25, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (234, '화이팅이다라고', 24, CURRENT_TIMESTAMP,'헬로우보이비밥', 45, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (235, '화이팅이다라고', 94, CURRENT_TIMESTAMP,'헬로우보이비밥', 35, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (236, '화이팅이다라고', 34, CURRENT_TIMESTAMP,'헬로우보이비밥', 15, '굿보이112', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (237, '화이팅이다라고00', 24, CURRENT_TIMESTAMP,'헬로우보이비밥', 115, '굿보이113', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (238, '화이팅이다라고123', 14, CURRENT_TIMESTAMP,'헬로우보이비밥', 25, '굿보이119', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (239, '화이팅이다라고4', 43, CURRENT_TIMESTAMP,'헬로우보이비밥', 35, '헬스보이', NULL, NULL, 0, 'C');