INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (901, 'HELLO1', 1, CURRENT_TIMESTAMP,'HITMAN', 10, 'GOODJOB1', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (902, 'HELLO2', 3, CURRENT_TIMESTAMP,'HITMAN2', 9, 'GOODJOB22', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (903, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (904, '징동다운굿', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (905, '징동다운444', 4111, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (906, '징동다운', 41, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (907, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (908, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (909, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (910, '징동다515운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (911, '징동굿다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO3', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (912, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWO55O', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (913, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN오오', 5, 'NAKWㅒㅖOO', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (914, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (915, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (916, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (917, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (918, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (919, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (920, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (921, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (922, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (923, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (924, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (925, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (926, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (927, '화이팅123이다라고', 6, CURRENT_TIMESTAMP,'헬로우보이11비밥', 5, '굿보이1441', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (928, '화이팅이다라고', 8, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이112', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (929, '화이팅이다라고23', 441, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (930, 'ohwowo', 50, CURRENT_TIMESTAMP,'헬로우보이비밥', 500, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (931, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (932, '화이팅이다라고', 4, CURRENT_TIMESTAMP,'헬로우보이비밥', 5, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (933, '화이팅이다라고', 84, CURRENT_TIMESTAMP,'헬로우보이비밥', 51, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (934, '화이팅이다라고', 54, CURRENT_TIMESTAMP,'헬로우보이비밥', 25, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (935, '화이팅이다라고', 24, CURRENT_TIMESTAMP,'헬로우보이비밥', 45, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (936, '화이팅이다라고', 94, CURRENT_TIMESTAMP,'헬로우보이비밥', 35, '굿보이11', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (937, '화이팅이다라고', 34, CURRENT_TIMESTAMP,'헬로우보이비밥', 15, '굿보이112', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (938, '화이팅이다라고00', 24, CURRENT_TIMESTAMP,'헬로우보이비밥', 115, '굿보이113', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (939, '화이팅이다라고123', 14, CURRENT_TIMESTAMP,'헬로우보이비밥', 25, '굿보이119', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (940, '화이팅이다라고4', 43, CURRENT_TIMESTAMP,'헬로우보이비밥', 35, '헬스보이', NULL, NULL, 0, 'C');