INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (1, 'HELLO1', 1, CURRENT_TIMESTAMP,'HITMAN', 10, 'GOODJOB1', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (2, 'HELLO2', 3, CURRENT_TIMESTAMP,'HITMAN2', 9, 'GOODJOB22', NULL, NULL, 0, 'C');

INSERT INTO NOTICEBOARD (BOARD_ID, BOARD_CN, BOARD_DONT_LIKE, BOARD_FST_REG_DT, BOARD_FST_REG_NM, BOARD_LIKE, BOARD_TITLE, BOARD_UPT_REG_DT, BOARD_UPT_REG_NM, BOARD_VIEWS, ROW_STAT_CD)
VALUES (3, '징동다운', 4, CURRENT_TIMESTAMP,'JDGDOWN', 5, 'NAKWOO', NULL, NULL, 0, 'C');